


quotes = [
    {"author": "Albert Einstein", "quote": "Imagination is more important than knowledge."},
    {"author": "Isaac Newton", "quote": "If I have seen further it is by standing on the shoulders of giants."},
    {"author": "Socrates", "quote": "The only true wisdom is in knowing you know nothing."},
    {"author": "Oscar Wilde", "quote": "Be yourself; everyone else is already taken."},
    {"author": "Mark Twain", "quote": "The secret of getting ahead is getting started."},
    {"author": "William Shakespeare", "quote": "To be, or not to be, that is the question."},
    {"author": "Confucius", "quote": "It does not matter how slowly you go as long as you do not stop."},
    {"author": "Friedrich Nietzsche", "quote": "He who has a why to live can bear almost any how."},
    {"author": "Ralph Waldo Emerson", "quote": "Do not go where the path may lead, go instead where there is no path and leave a trail."},
    {"author": "Leonardo da Vinci", "quote": "Learning never exhausts the mind."},
    {"author": "Aristotle", "quote": "Happiness depends upon ourselves."},
    {"author": "Walt Disney", "quote": "The way to get started is to quit talking and begin doing."},
    {"author": "George Bernard Shaw", "quote": "Life isn't about finding yourself. Life is about creating yourself."},
    {"author": "Henry David Thoreau", "quote": "Go confidently in the direction of your dreams. Live the life you have imagined."},
    {"author": "Dalai Lama", "quote": "The purpose of our lives is to be happy."},
    {"author": "Mahatma Gandhi", "quote": "Be the change that you wish to see in the world."},
    {"author": "Nelson Mandela", "quote": "It always seems impossible until it's done."},
    {"author": "Martin Luther King Jr.", "quote": "I have a dream."},
    {"author": "Mother Teresa", "quote": "Not all of us can do great things. But we can do small things with great love."},
    {"author": "Vincent Van Gogh", "quote": "I dream my painting and I paint my dream."},
    {"author": "Helen Keller", "quote": "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart."},
    {"author": "John Lennon", "quote": "Life is what happens when you're busy making other plans."},
    {"author": "Charles Darwin", "quote": "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change."},
    {"author": "Pablo Picasso", "quote": "Every child is an artist. The problem is how to remain an artist once he grows up."},
    {"author": "Winston Churchill", "quote": "Success is not final, failure is not fatal: it is the courage to continue that counts."},
    {"author": "Benjamin Franklin", "quote": "An investment in knowledge pays the best interest."},
    {"author": "Abraham Lincoln", "quote": "Whatever you are, be a good one."},
    {"author": "J.K. Rowling", "quote": "It is our choices that show what we truly are, far more than our abilities."},
    {"author": "Steve Jobs", "quote": "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work."},
    {"author": "Elon Musk", "quote": "When something is important enough, you do it even if the odds are not in your favor."},
    {"author": "Marie Curie", "quote": "Nothing in life is to be feared, it is only to be understood."},
    {"author": "Jane Austen", "quote": "There is no charm equal to tenderness of heart."},
    {"author": "Edgar Allan Poe", "quote": "All that we see or seem is but a dream within a dream."},
    {"author": "Voltaire", "quote": "Judge a man by his questions rather than by his answers."},
    {"author": "Confucius", "quote": "Real knowledge is to know the extent of one's ignorance."},
    {"author": "Buddha", "quote": "The mind is everything. What you think you become."},
    {"author": "Plato", "quote": "The greatest wealth is to live content with little."},
    {"author": "George Orwell", "quote": "In a time of deceit, telling the truth is a revolutionary act."},
    {"author": "Anne Frank", "quote": "How wonderful it is that nobody need wait a single moment before starting to improve the world."},
    {"author": "Albert Camus", "quote": "In the depth of winter, I finally learned that there was in me an invincible summer."},
    {"author": "Stephen Hawking", "quote": "Intelligence is the ability to adapt to change."},
    {"author": "Marcus Aurelius", "quote": "The happiness of your life depends upon the quality of your thoughts."},
    {"author": "Julius Caesar", "quote": "Experience is the teacher of all things."},
    {"author": "Thomas Jefferson", "quote": "I find that the harder I work, the more luck I seem to have."},
    {"author": "Confucius", "quote": "Our greatest glory is not in never falling, but in rising every time we fall."},
    {"author": "Soren Kierkegaard", "quote": "Life can only be understood backwards; but it must be lived forwards."},
    {"author": "Henry Ford", "quote": "Whether you think you can, or you think you can't—you're right."},
    {"author": "Maya Angelou", "quote": "You will face many defeats in life, but never let yourself be defeated."},
    {"author": "Homer", "quote": "There is a time for many words, and there is also a time for sleep."},
    {"author": "Emily Dickinson", "quote": "Hope is the thing with feathers that perches in the soul—and sings the tunes without the words—and never stops at all."},
    {"author": "Mahatma Gandhi", "quote": "Be the change that you wish to see in the world."},
    {"author": "David Bowie", "quote": "I don't know where I'm going from here, but I promise it won't be boring."},
    {"author": "Rumi", "quote": "The wound is the place where the Light enters you."},
    {"author": "Lao Tzu", "quote": "A journey of a thousand miles begins with a single step."},
    {"author": "Buddha", "quote": "The mind is everything. What you think you become."},
    {"author": "Steve Jobs", "quote": "Your time is limited, so don't waste it living someone else's life."},
    {"author": "Malala Yousafzai", "quote": "One child, one teacher, one pen, and one book can change the world."},
    {"author": "Albert Schweitzer", "quote": "Success is not the key to happiness. Happiness is the key to success."},
    {"author": "Jane Goodall", "quote": "What you do makes a difference, and you have to decide what kind of difference you want to make."},
    {"author": "C.S. Lewis", "quote": "You can make anything by writing."},
    {"author": "F. Scott Fitzgerald", "quote": "The test of a first-rate intelligence is the ability to hold two opposed ideas in mind at the same time and still retain the ability to function."},
    {"author": "Emily Brontë", "quote": "Whatever our souls are made of, his and mine are the same."},
    {"author": "Jack Kerouac", "quote": "The only truth is music."},
    {"author": "Pradelson Francois", "quote": "Time never stops, but it always leaves traces on those who make the most of it."},
    {"author": "Pradelson Francois", "quote": "True strength isn’t measured by success, but by how many times you decide to try just once more"},
    {"author": "Billie Holiday", "quote": "If I can't have you, I want you to be happy."},
    {"author": "Walt Whitman", "quote": "Keep your face always toward the sunshine—and shadows will fall behind you."},
    {"author": "Leo Tolstoy", "quote": "Everyone thinks of changing the world, but no one thinks of changing himself."},
    ]